version: "3"

services:
  ckan:
    profiles: ["full"]
    build:
      context: docker/ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
    ports:
      - "${CKAN_PORT}:5000"
    volumes:
      #- .:/srv/app/src_extensions/ckanext-iaea
      - ckan_storage:/var/lib/ckan

  # ckan-worker-default:
  #   build:
  #     context: docker/ckan/
  #     dockerfile: Dockerfile
  #     args:
  #       - TZ=${TZ}
  #   env_file:
  #     - .env
  #   links:
  #     - db
  #     - solr
  #     - redis
  #   volumes:
  #     - .:/srv/app/src_extensions/ckanext-iaea
  #     - ckan_storage:/var/lib/ckan
  #   command: ["/srv/app/start_ckan_worker.sh", "default"]
  
  # ckan-worker-bulk:
  #   build:
  #     context: docker/ckan/
  #     dockerfile: Dockerfile
  #     args:
  #       - TZ=${TZ}
  #   env_file:
  #     - .env
  #   links:
  #     - db
  #     - solr
  #     - redis
  #   volumes:
  #     - .:/srv/app/src_extensions/ckanext-iaea
  #     - ckan_storage:/var/lib/ckan
  #   command: ["/srv/app/start_ckan_worker.sh", "bulk"]

  # ckan-worker-priority:
  #   build:
  #     context: docker/ckan/
  #     dockerfile: Dockerfile
  #     args:
  #       - TZ=${TZ}
  #   env_file:
  #     - .env
  #   links:
  #     - db
  #     - solr
  #     - redis
  #   volumes:
  #     - .:/srv/app/src_extensions/ckanext-iaea
  #     - ckan_storage:/var/lib/ckan
  #   command: ["/srv/app/start_ckan_worker.sh", "priority"]

  db:
    container_name: iaea_db
    env_file:
      - .env
    environment:
      - "PGDATA=/var/lib/postgresql/data/dbdata"
    ports:
      - "5432:5432"
    build:
      context: docker/postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data/dbdata

  solr:
    image: ckan/ckan-solr:master
    container_name: iaea_solr
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: iaea_redis
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  ckan_storage:
  pg_data:
  solr_data: