version: "3"

services:
  ckan:
    profiles: ["full"]
    hostname: ckan.iaea.local
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - datapusher
      - redis
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - .:/srv/app/src_extensions/ckanext-iaea
      - ckan_storage:/var/lib/ckan

  ckan-worker-default:
    profiles: ["full"]
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - datapusher
      - redis
    volumes:
      - .:/srv/app/src_extensions/ckanext-iaea
      - ckan_storage:/var/lib/ckan
    command: ["/srv/app/start_ckan_worker.sh", "default"]
  
  ckan-worker-bulk:
    profiles: ["full"]
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - datapusher
      - redis
    volumes:
      - .:/srv/app/src_extensions/ckanext-iaea
      - ckan_storage:/var/lib/ckan
    command: ["/srv/app/start_ckan_worker.sh", "bulk"]

  ckan-worker-priority:
    profiles: ["full"]
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - datapusher
      - redis
    volumes:
      - .:/srv/app/src_extensions/ckanext-iaea
      - ckan_storage:/var/lib/ckan
    command: ["/srv/app/start_ckan_worker.sh", "priority"]

  db:
    container_name: db
    env_file:
      - .env
    environment:
      - "PGDATA=/var/lib/postgresql/data/dbdata"
    ports:
      - "5432:5432"
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data/dbdata

  solr:
    container_name: solr
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    build:
      context: solr/
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  ckan_storage:
  pg_data:
  solr_data: